version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - gosec         # Security-focused linter
    - gocyclo       # Check cyclomatic complexity
    - errorlint     # Check error wrapping

formatters:
  enable:
    - gofmt         # Format code
    - goimports     # Format imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

